---
- become: yes
  block:
    - name: fetch kubectl from control plane
      fetch:
        dest: "{{ playbook_dir + '/kubectl' }}"
        flat: true
        group: jenkins
        owner: jenkins
        mode: 0600
        src: "/usr/bin/kubectl"
      when: "inventory_hostname in groups['controlplane']"

    - name: Copy kubectl to Jumper Node
      copy:
        dest: "/usr/bin/kubectl"
        group: jenkins
        owner: jenkins
        mode: 0755
        src: "{{ playbook_dir + '/kubectl' }}"
      when: "inventory_hostname in groups['jumper']" 

    - name: fetch admin.conf from control plane
      fetch:
        dest: "{{ playbook_dir + '/admin.conf' }}"
        flat: true
        group: jenkins
        owner: jenkins
        mode: 0600
        src: "/etc/kubernetes/admin.conf"
      when: "inventory_hostname in groups['controlplane']"

    - name: Create kubernetes directory
      file:
        group: jenkins
        owner: jenkins
        path: "/etc/kubernetes" 
        state: directory 
        mode: 0755
      when: "inventory_hostname in groups['jumper']"

    - name: Copy admin.conf to Jumper Node
      copy:
        dest: "/etc/kubernetes/admin.conf"
        group: jenkins
        owner: jenkins
        mode: 0600
        src: "{{ playbook_dir + '/admin.conf' }}"
      when: "inventory_hostname in groups['jumper']"

    - name: Ensure jenkins user's .kube dir exist
      file:
        group: jenkins
        owner: jenkins
        mode: 0750
        path: "{{ jenkins_home }}/.kube"
        state: directory

    - name: Copy Kubernetes admin config to jenkins user
      copy:
        dest: "{{ jenkins_home }}/.kube/config"
        src: /etc/kubernetes/admin.conf
        mode: 0600
        owner: jenkins
        group: jenkins
        remote_src: yes
        force: yes

    - name: Ensure ubuntu user's .kube dir exist
      file:
        group: ubuntu
        owner: ubuntu
        mode: 0750
        path: /home/ubuntu/.kube
        state: directory

    - name: Allow ubuntu user to Manage Kubernetes
      copy:
        dest: /home/ubuntu/.kube/config
        src: /etc/kubernetes/admin.conf
        remote_src: yes
        mode: 0600
        owner: ubuntu
        group: ubuntu
        force: yes



